### PR TITLE
add cmdline binary

### PR DESCRIPTION
**Pull request by KristofferC**
This allows one to execute Pkg3 commands without explicitly starting Julia with `juliapkg ...`. Perhaps this could be added in the bin directory of julia.

The startup time is still horrible but that is probably related to #28

image

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Is this usable with the compilation time?

**Comment by KristofferC** [comment]
Not as a package (method overwrites are really bad for compilation)  but as a stdlib package, where the method overrides have been swapped out for hooks into Base, it is at least decent. However, perhaps we should just encourage Repl use.

**Comment by KristofferC** [comment]
Our REPL is awsome, we should make it the preferred way of using Pkg3.

**Comment by StefanKarpinski** [comment]
Agree! Perl always had the best package manager and it was based on its REPL.

**Comment by ExpandingMan** [comment]
As much as I agree that the REPL is awesome, it would be very useful to have a command line entry point to the package manager because this will be extremely useful for container set up scripts such as dockerfiles and AWS scripts.  I think a `juliapkg` command would be awesome, any chance of reviving this?

**Pull request closed without merging**
