### PR TITLE
Support VersionSet's when reading legacy METADATA 

### LINKED ISSUE #231: Wrong version range for AbstractFFTs 0.3+ in Uncurated registry
(I hope I'm correct to report issues in the automated `METADATA` to `Uncurated` translation here.)

AbstractFFTs 0.3.0 and 0.3.1 have the Julia version requirement
```
julia 0.6 0.7.0-DEV.602 0.7.0-DEV.3449
```
I.e. the package should not be installable on Julia versions `0.7.0-DEV.602` (inclusive) to `0.7.0-DEV.3449` (exclusive), but newer Julia versions are ok. However, it gets translated to
```
["0.3"]
julia = "0.6"
```
This makes these versions uninstallable on current Julia master.

### PR DESCRIPTION
**Pull request by martinholters**
Fixes #231. To be able to test this locally, I've included #285 here. I'm getting this delta on the registry:
```diff
diff --git a/A/AbstractFFTs/Compat.toml b/A/AbstractFFTs/Compat.toml
index ec3140211..3acfdf903 100644
--- a/A/AbstractFFTs/Compat.toml
+++ b/A/AbstractFFTs/Compat.toml
@@ -1,5 +1,2 @@
-["0.0-0.2"]
+["0.0-0.3"]
 julia = "0.6-0.7"
-
-["0.3"]
-julia = "0.6"
diff --git a/G/GLVisualize/Compat.toml b/G/GLVisualize/Compat.toml
index da440675c..33d3fbd04 100644
--- a/G/GLVisualize/Compat.toml
+++ b/G/GLVisualize/Compat.toml
@@ -67,7 +67,7 @@ GeometryTypes = "0.2"
 GLAbstraction = "0.3.2"
 GLWindow = "0.3.3"
 Packing = "0.0.4"
-Reactive = "0.3.0-0.3.6"
+Reactive = ["0.3.0-0.3.6", "0.5-0.6"]
 
 ["0.3-0.7"]
 AxisArrays = "0.0-0.2"
diff --git a/G/Geodesy/Compat.toml b/G/Geodesy/Compat.toml
index bd837cdec..96bac0626 100644
--- a/G/Geodesy/Compat.toml
+++ b/G/Geodesy/Compat.toml
@@ -24,7 +24,7 @@ StaticArrays = "0.0.4-0.7"
 
 ["0.3.1"]
 Compat = "0.17-0.64"
-StaticArrays = "0.0.4-0.3"
+StaticArrays = ["0.0.4-0.3", "0.5-0.7"]
 
 ["0.4"]
 julia = "0.6-0.7"
diff --git a/R/RDatasets/Compat.toml b/R/RDatasets/Compat.toml
index 4ee58e500..4c441085c 100644
--- a/R/RDatasets/Compat.toml
+++ b/R/RDatasets/Compat.toml
@@ -1,12 +1,12 @@
 ["0.0"]
 DataArrays = "0.0-0.6"
 
+["0.0-0.1"]
+DataFrames = "0.1-0.10"
+
 ["0.0-0.1.1"]
 julia = "0.2-0.7"
 
-["0.0-0.2"]
-DataFrames = "0.1-0.10"
-
 ["0.1.0"]
 DataArrays = "0.1-0.6"
 
@@ -27,6 +27,7 @@ Compat = "0.0-0.64"
 
 ["0.2"]
 julia = "0.4-0.7"
+DataFrames = ["0.1-0.10", "0.11.4-0.11.6"]
 FileIO = "0.0-0.7"
 RData = "0.0-0.4"
 
```
AFAICT, these are all valid, desirable changes.

I'm clueless about the `sha1map.toml`/`stdlib.toml`; I've included a commit with the changes I'm seeing in case that needs inspection.

### CODE REVIEW

**Comment by KristofferC** [comment]
The toml files are just caches for when you want to recreate the registry on a new machine.

**Comment by KristofferC** [comment]
Thanks for the fix. Looks good from my p.o.v.

**Comment by StefanKarpinski** [comment]
This looks good to me. Somewhat amazingly, I think that when I originally wrote this there were no non-interval version sets in any registered requires files.

**Comment by martinholters** [comment]
Bump. Being able to compute an FFT in a Pkg3-based environment would be nice...

**Comment by KristofferC** [comment]
Sorry, yes. Will get on this.

**Comment by martinholters** [comment]
My bad for tying you up in a tiring discussion over at https://github.com/JuliaLang/Compat.jl/pull/547 :smile:

**Comment by KristofferC** [comment]
Meh, shouldnt have squashed. Oh well.

**Comment by martinholters** [comment]
Thanks! When can I expect an accordingly updated registry?

**Comment by KristofferC** [comment]
https://github.com/JuliaRegistries/Uncurated/commit/eb9a959331dd162e588652cb01c0d26787b181ac

**Pull request merged**
