### PR TITLE
 Build dependent packages and support varargs in API.build

### PR DESCRIPTION
**Pull request by vdayanand**
Previously ```build``` command was not building dependent packages.
Added support for varargs in `Pkg3.API.build,` as present in `Pkg.build`
```
julia> Pkg3.build("PyCall", "DataFrames")
INFO: Resolving package versions
INFO: Building Conda [b26546424d5f3ac3]...
INFO:  → /home/osboxes/.julia/packages/N8e4/u0lj/deps/build.log
INFO: Building PyCall [2ba54612238a85ee]...
INFO:  → /home/osboxes/.julia/packages/mbAM/vGCc/deps/build.log
INFO: Building SpecialFunctions [a052147e601e7926]...
INFO:  → /home/osboxes/.julia/packages/FTLa/YKDc/deps/build.log

```

### CODE REVIEW

**Comment by KristofferC** [comment]
Couldn't

https://github.com/JuliaLang/Pkg3.jl/blob/317e3127c9ee2611fa3ec0d5cccd582ac3de3e5d/src/Operations.jl#L422-L440

just add the dependencies (if they have a build file) to `builds` defined at

https://github.com/JuliaLang/Pkg3.jl/blob/317e3127c9ee2611fa3ec0d5cccd582ac3de3e5d/src/Operations.jl#L445

?

It seems excessive to run the resolver and everything here because there shouldn't be anything to resolve?

**Comment by vdayanand** [comment]
@KristofferC  Thanks for the suggestion.

**Comment by vdayanand** [comment]
fixes code broken by #94

**Comment by KristofferC** [comment]
This looks good to me now. We are not using the resolver nor hitting any of the registry files. Any thoughts @StefanKarpinski

**Comment by StefanKarpinski** [comment]
Seems good to me. Are we expected CI to pass these days or not?

**Comment by KristofferC** [comment]
On 0.6 yes (which this does)

**Comment by StefanKarpinski** [comment]
Merge at will then!

**Comment by KristofferC** [comment]
Although we do not test this command yet... But I think @vdayanand has tested this quite extensively locally.

**Pull request merged**
