### PR TITLE
thread a "PkgContext" through most of the Operations.

### PR DESCRIPTION
**Pull request by KristofferC**
This contains settings and state that needs to be passed around

Removes the `GLOBAL_SETTINGS` struct.

Based on the comment in #122:

> A pretty large amount of options and state need to be passed around between all of these functions and that will only grow as we add more functionality to the interface. We should probably bite the bullet and have an type that wraps all of the options which can also have input, output and error streams in it.

### CODE REVIEW

**Comment by KristofferC** [comment]
Yeah, I thought the same. Right now you can just use keyword arguments to each API method to set fields of the `PkgContext` though, like `Pkg3.add("JSON"; preview = true)` sets the `preview` field of the `PkgContext` so there is no need to create the context yourself.

**Comment by StefanKarpinski** [comment]
Sure, but I have to see the type name in the code base itself. And it's not externally visible, so what's the harm in a shorter, more context-specific (see what I did there?) name?

**Comment by KristofferC** [comment]
Yeah, that's why "I thought the same". The rest was just a remark.

**Comment by KristofferC** [comment]
Changed it to just `Context`.

**Pull request merged**
